# Generated by Django 4.2.14 on 2024-08-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="apps",
        ),
    ]
