# Generated by Django 4.2.14 on 2024-08-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_apps"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
